package io.github.a7asoft.nfcemv.extract

import io.github.a7asoft.nfcemv.validation.isValidLuhn
import kotlin.jvm.JvmInline

/**
 * A primary account number (PAN) wrapped to keep raw digits off
 * `toString()`, stack traces, and string interpolation.
 *
 * Construction throws [IllegalArgumentException] when [raw]:
 * - is not 12 to 19 ASCII digits in length, or
 * - fails the Luhn / mod-10 check per ISO/IEC 7812-1 Annex B.
 *
 * Length range covers the modern ISO/IEC 7812-1 PAN range that masks
 * cleanly under the 6-prefix + last-4 PCI DSS Req 3.4 rule (12d Maestro
 * minimum through 19d ISO max).
 *
 * [toString] returns the PCI-DSS-compliant masked form: first 6 (BIN) +
 * `*` for the middle digits + last 4. The raw value is NEVER embedded in
 * `toString`, in `equals`/`hashCode` (auto-generated by the value class
 * and used only for comparison), in `require` failure messages, or in any
 * other built-in surface.
 *
 * The only API to retrieve the raw value is [unmasked]. Callers MUST treat
 * the return value as PCI-scoped and route it through a typed extractor or
 * an authenticated transport. Never log it, never persist it, never
 * compare it via `String.equals` (use `Pan` equality instead).
 *
 * Equality is auto-generated by the value class and is value-based on the
 * raw form. Two `Pan` instances with the same digits are equal; the raw
 * value is not exposed by the comparison itself.
 */
@JvmInline
public value class Pan(private val raw: String) {

    init {
        require(raw.length in MIN_LENGTH..MAX_LENGTH) {
            "PAN length must be $MIN_LENGTH to $MAX_LENGTH digits, was ${raw.length}"
        }
        require(raw.isValidLuhn()) { "PAN failed Luhn check" }
    }

    /**
     * Returns the underlying digit string. PCI-scoped: the caller is
     * responsible for not logging, persisting, or transmitting this value.
     *
     * A future logging hook (per #v0.4.0 `Logger`) will instrument this
     * accessor to emit a warning when called from production code.
     */
    public fun unmasked(): String = raw

    override fun toString(): String =
        raw.take(VISIBLE_PREFIX) +
            "*".repeat(raw.length - MASK_RESERVED) +
            raw.takeLast(VISIBLE_SUFFIX)

    public companion object {
        internal const val MIN_LENGTH: Int = 12
        internal const val MAX_LENGTH: Int = 19
        private const val VISIBLE_PREFIX: Int = 6
        private const val VISIBLE_SUFFIX: Int = 4
        private const val MASK_RESERVED: Int = VISIBLE_PREFIX + VISIBLE_SUFFIX
    }
}
